version: '3.8'

services:
  splunk:
    image: splunk/splunk:9.1
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=Chang3dPwd!
      - SPLUNK_ENABLE_LISTEN=9997
      - SPLUNK_ADD=monitor /opt/splunk/var/log/dummy_app.log
    volumes:
      - ./splunk/ssl:/opt/splunk/etc/auth
      - ./splunk/data:/opt/splunk/var
    ports:
      - "8000:8000"    # Web UI
      - "8088:8088"    # HTTP Event Collector (HEC)
      - "8089:8089"    # Management Port (REST API)
      - "9997:9997"    # Forwarding Port
    restart: unless-stopped
